---
# defaults file for gentoo_build
nvme: false
livecd_boot_efi_usb: "/dev/sdb"
livecd_boot_efi_usb_partition: "{{ livecd_boot_efi_usb }}1"
#livecd_primary_disk: "/dev/sda"
livecd_primary_disk: "/dev/nvme0n1"
# NVME partions are 'p1', not '1', so below is used for non-nvme disks
# Playbook has set_fact to set this variable correctly for NVME disks
livecd_primary_disk_partition: "{{ livecd_primary_disk }}1"
# livecd_usb_luks_key: "/mnt/usb/luks-key.gpg"
livecd_usb_luks_key: "/root/luks-key.gpg"
livecd_cryptsetup_cipher: serpent-xts-plain64
livecd_cryptsetup_key_size: 512
livecd_luks_discards: "--allow-discards"  # enable with: --allow-discards
livecd_cryptsetup_hash: whirlpool
livecd_luks_optional: false
livecd_luks_vol: gentoo
livecd_filesystem_type: xfs
livecd_lvm_vg: vg1
livecd_lvm_pv: /dev/mapper/gentoo
livecd_lvm_lvs:
  lv:
    swap:
      size: 17G
    root:
      size: 5G
    home:
      size: 30G
    opt:
      size: 10G
    temp:
      size: 5G
    var:
      size: 20G

livecd_stage3_url: https://gentoo.osuosl.org/releases/amd64/autobuilds
livecd_stage3_date: 20230305T164658Z

livecd_release_fingerprint: 13EBBDBEDE7A12775DFDB1BABB572E0E2D182910

livecd_make_cpu_flags: "mmx mmxext sse sse2"
livecd_video_card: "intel vesa"
# ls /usr/share/zoneinfo
livecd_timezone: "US/Eastern"
livecd_kernel_sources: "vanilla-sources"
