---
- name: Deploy gentoo_build
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check if requirements.yml files exists
      ansible.builtin.stat:
        path: "requirements.yml"
      register: file_data

    - name: Install galaxy requirements  # noqa run-once
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
      changed_when: false
      delegate_to: localhost
      run_once: true
      check_mode: false
      become: true
      when:
        - file_data.stat.exists


  roles:
    - {role: 'gentoo_build'}

  post_tasks:
    - name: Get list of Galaxy requirement roles  # noqa run-once
      ansible.builtin.shell: set -o pipefail; \
        ansible-galaxy role list | grep -i '-' | grep -iv 'gentoo_build' | \
        cut -d ',' -f1 | sed 's/- //g'
      delegate_to: localhost
      check_mode: false
      run_once: true
      changed_when: false
      become: false
      register: galaxy_role_list

    - name: Remove galaxy requirements  # noqa run-once
      #
      ansible.builtin.command: ansible-galaxy remove {{ item }}
      #
      changed_when: false
      delegate_to: localhost
      run_once: true
      check_mode: false
      become: false
      with_items:
        #
        - "{{ galaxy_role_list.stdout }}"
        #
      when:
        - file_data.stat.exists
