---
- name: Is chroot setup in ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "chroot"
  check_mode: true
  register: chroot_enabled

- name: Before chroot
  include: before_chroot.yml
  when: not chroot_enabled

- name: Include After chroot stuff
  include: after_chroot.yml
  when: chroot_enabled
